ecs:
  image: golang:1.5.0
  command: ["go", "build"]
  working_dir: '/go/src/github.com/caiguanhao/aliyun/ecs'
  environment:
    - ALIYUN_ACCESS_KEY
    - ALIYUN_ACCESS_SECRET
  volumes:
    - '.:/go/src/github.com/caiguanhao/aliyun'

oss:
  image: golang:1.5.0
  command: ["go", "build"]
  working_dir: '/go/src/github.com/caiguanhao/aliyun/oss'
  environment:
    - API_PREFIX
    - BUCKET
    - ALIYUN_ACCESS_KEY
    - ALIYUN_ACCESS_SECRET
  volumes:
    - '.:/go/src/github.com/caiguanhao/aliyun'
